apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-books
    environment: Development
  name: order-books
  namespace: exchange
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  - name: grpc
    port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: order-books
  sessionAffinity: None
  type: ClusterIP
