name: Release MyNoSql nuget

on:
  push:
    tags: "mynosql-*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build --configuration Release /p:Version=${GITHUB_REF#refs/tags/mynosql-}
    - name: Test
      run: dotnet test --no-build --configuration Release
    - name: Create the package
      run: dotnet pack --configuration Release src/OrderBooks.MyNoSql /p:Version=${GITHUB_REF#refs/tags/mynosql-}
    - name: Publish the package to GPR
      run: dotnet nuget push src/OrderBooks.MyNoSql/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}
